In [1]:
import numpy as np
import pandas as pd
import sklearn

In [2]:
df=pd.read_csv(r"C:\Users\vutuk\Downloads\banking_loan_approval_dataset_100k.csv")
df.head()

,age,job,marital,education,default,balance,housing_loan,personal_loan,contact,day,month,duration,campaign,pdays,previous,poutcome,LOAN_APPROVAL
0,56,retired,married,tertiary,0,102856,1,0,cellular,21,sep,798,16,343,0,failure,1
1,69,student,single,tertiary,1,64751,0,0,cellular,20,may,250,15,466,3,success,0
2,46,services,divorced,tertiary,0,88210,1,1,telephone,3,mar,268,15,476,2,success,1
3,32,services,married,primary,0,39552,0,1,cellular,13,aug,671,4,487,8,unknown,1
4,60,student,divorced,secondary,0,14103,0,0,cellular,9,jul,1859,5,242,1,unknown,1

In [3]:
df.head()

,age,job,marital,education,default,balance,housing_loan,personal_loan,contact,day,month,duration,campaign,pdays,previous,poutcome,LOAN_APPROVAL
0,56,retired,married,tertiary,0,102856,1,0,cellular,21,sep,798,16,343,0,failure,1
1,69,student,single,tertiary,1,64751,0,0,cellular,20,may,250,15,466,3,success,0
2,46,services,divorced,tertiary,0,88210,1,1,telephone,3,mar,268,15,476,2,success,1
3,32,services,married,primary,0,39552,0,1,cellular,13,aug,671,4,487,8,unknown,1
4,60,student,divorced,secondary,0,14103,0,0,cellular,9,jul,1859,5,242,1,unknown,1

In [4]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance',
       'housing_loan', 'personal_loan', 'contact', 'day', 'month', 'duration',
       'campaign', 'pdays', 'previous', 'poutcome', 'LOAN_APPROVAL'],
      dtype='object')

## step 1 - split the data into X(inputs) and y(output)

In [5]:
X = df.drop('LOAN_APPROVAL',axis=1)

In [6]:
y = df[['LOAN_APPROVAL']]

## step 2 - split the data into train and test (80-20)

In [7]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test  = train_test_split(X,y,train_size=0.8,random_state=4)

In [8]:
## step 3 - Feature engineering on Training Data ( X_train and y_train )

In [9]:
X_train

,age,job,marital,education,default,balance,housing_loan,personal_loan,contact,day,month,duration,campaign,pdays,previous,poutcome
8446,67,retired,single,secondary,0,97896,0,1,cellular,13,jun,1204,2,351,5,unknown
19150,54,admin,married,secondary,0,78910,1,0,cellular,28,sep,720,5,102,4,failure
46825,74,services,single,primary,0,46296,1,1,telephone,19,apr,228,4,483,2,success
95011,60,student,single,primary,0,9093,0,0,telephone,15,may,891,12,269,5,unknown
68234,43,services,divorced,secondary,0,89168,1,0,cellular,23,sep,1600,3,499,8,unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23346,32,management,divorced,primary,0,145537,0,0,telephone,24,feb,418,13,280,4,success
11863,30,retired,divorced,primary,0,142611,1,1,telephone,15,jan,1285,14,99,6,success
92599,41,student,married,secondary,0,81233,1,0,cellular,2,apr,1945,1,171,4,unknown
73902,32,admin,married,primary,1,98101,0,1,cellular,14,jul,535,4,269,1,unknown
83066,34,student,single,primary,0,90817,1,0,telephone,21,jul,248,12,2,7,failure

In [10]:
cat_df = X_train.select_dtypes(include = 'object')

In [11]:
cat_df

              job   marital  education    contact month poutcome
8446      retired    single  secondary   cellular   jun  unknown
19150       admin   married  secondary   cellular   sep  failure
46825    services    single    primary  telephone   apr  success
95011     student    single    primary  telephone   may  unknown
68234    services  divorced  secondary   cellular   sep  unknown
...           ...       ...        ...        ...   ...      ...
23346  management  divorced    primary  telephone   feb  success
11863     retired  divorced    primary  telephone   jan  success
92599     student   married  secondary   cellular   apr  unknown
73902       admin   married    primary   cellular   jul  unknown
83066     student    single    primary  telephone   jul  failure

[80000 rows x 6 columns]

In [12]:
from sklearn.preprocessing import OneHotEncoder

OHE = OneHotEncoder(sparse_output=False).set_output(transform='pandas')

cat_df_trans = OHE.fit_transform(cat_df)

In [13]:
cat_df_trans

,job_admin,job_management,job_retired,job_services,job_student,job_technician,marital_divorced,marital_married,marital_single,education_primary,...,month_jul,month_jun,month_mar,month_may,month_nov,month_oct,month_sep,poutcome_failure,poutcome_success,poutcome_unknown
8446,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
19150,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
46825,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
95011,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
68234,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23346,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
11863,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
92599,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
73902,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
83066,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [14]:
OHE.categories_

[array(['admin', 'management', 'retired', 'services', 'student',
        'technician'], dtype=object),
 array(['divorced', 'married', 'single'], dtype=object),
 array(['primary', 'secondary', 'tertiary'], dtype=object),
 array(['cellular', 'telephone'], dtype=object),
 array(['apr', 'aug', 'dec', 'feb', 'jan', 'jul', 'jun', 'mar', 'may',
        'nov', 'oct', 'sep'], dtype=object),
 array(['failure', 'success', 'unknown'], dtype=object)]

In [15]:
num_df = X_train[['age','balance','day','duration','campaign','pdays']]

In [16]:
no_trans = X_train[['default','housing_loan','personal_loan','previous']]

In [17]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler().set_output(transform='pandas')

num_df_trans = scaler.fit_transform(num_df)

In [18]:
num_df_trans

            age   balance       day  duration  campaign  pdays
8446   0.875000  0.657223  0.413793  0.596242  0.055556  0.704
19150  0.642857  0.532313  0.931034  0.350432  0.222222  0.206
46825  1.000000  0.317743  0.620690  0.100559  0.166667  0.968
95011  0.750000  0.072982  0.482759  0.437278  0.611111  0.540
68234  0.446429  0.599801  0.758621  0.797359  0.111111  1.000
...         ...       ...       ...       ...       ...    ...
23346  0.250000  0.970657  0.793103  0.197054  0.666667  0.562
11863  0.214286  0.951407  0.482759  0.637379  0.722222  0.200
92599  0.410714  0.547596  0.034483  0.972575  0.000000  0.344
73902  0.250000  0.658572  0.448276  0.256475  0.166667  0.540
83066  0.285714  0.610650  0.689655  0.110716  0.611111  0.006

[80000 rows x 6 columns]

In [19]:
num_df_trans.reset_index(inplace=True)

In [20]:
cat_df_trans.reset_index(inplace=True)

In [21]:
no_trans.reset_index(inplace=True)

In [22]:
X_train_trans = pd.concat([num_df_trans,cat_df_trans,no_trans],axis=1)

In [23]:
X_train_trans

,index,age,balance,day,duration,campaign,pdays,index,job_admin,job_management,...,month_oct,month_sep,poutcome_failure,poutcome_success,poutcome_unknown,index,default,housing_loan,personal_loan,previous
0,8446,0.875000,0.657223,0.413793,0.596242,0.055556,0.704,8446,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,8446,0,0,1,5
1,19150,0.642857,0.532313,0.931034,0.350432,0.222222,0.206,19150,1.0,0.0,...,0.0,1.0,1.0,0.0,0.0,19150,0,1,0,4
2,46825,1.000000,0.317743,0.620690,0.100559,0.166667,0.968,46825,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,46825,0,1,1,2
3,95011,0.750000,0.072982,0.482759,0.437278,0.611111,0.540,95011,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,95011,0,0,0,5
4,68234,0.446429,0.599801,0.758621,0.797359,0.111111,1.000,68234,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,68234,0,1,0,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,23346,0.250000,0.970657,0.793103,0.197054,0.666667,0.562,23346,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,23346,0,0,0,4
79996,11863,0.214286,0.951407,0.482759,0.637379,0.722222,0.200,11863,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,11863,0,1,1,6
79997,92599,0.410714,0.547596,0.034483,0.972575,0.000000,0.344,92599,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,92599,0,1,0,4
79998,73902,0.250000,0.658572,0.448276,0.256475,0.166667,0.540,73902,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,73902,1,0,1,1
79999,83066,0.285714,0.610650,0.689655,0.110716,0.611111,0.006,83066,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,83066,0,1,0,7

In [24]:
X_train_trans.pop('index')

       index  index  index
0       8446   8446   8446
1      19150  19150  19150
2      46825  46825  46825
3      95011  95011  95011
4      68234  68234  68234
...      ...    ...    ...
79995  23346  23346  23346
79996  11863  11863  11863
79997  92599  92599  92599
79998  73902  73902  73902
79999  83066  83066  83066

[80000 rows x 3 columns]

In [25]:
X_train_trans

,age,balance,day,duration,campaign,pdays,job_admin,job_management,job_retired,job_services,...,month_nov,month_oct,month_sep,poutcome_failure,poutcome_success,poutcome_unknown,default,housing_loan,personal_loan,previous
0,0.875000,0.657223,0.413793,0.596242,0.055556,0.704,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0,0,1,5
1,0.642857,0.532313,0.931034,0.350432,0.222222,0.206,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0,1,0,4
2,1.000000,0.317743,0.620690,0.100559,0.166667,0.968,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0,1,1,2
3,0.750000,0.072982,0.482759,0.437278,0.611111,0.540,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0,0,0,5
4,0.446429,0.599801,0.758621,0.797359,0.111111,1.000,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0,1,0,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,0.250000,0.970657,0.793103,0.197054,0.666667,0.562,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0,0,0,4
79996,0.214286,0.951407,0.482759,0.637379,0.722222,0.200,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0,1,1,6
79997,0.410714,0.547596,0.034483,0.972575,0.000000,0.344,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0,1,0,4
79998,0.250000,0.658572,0.448276,0.256475,0.166667,0.540,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1,0,1,1
79999,0.285714,0.610650,0.689655,0.110716,0.611111,0.006,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0,1,0,7

In [26]:
y_train.reset_index(inplace=True)

In [27]:
y_train.pop('index')

0         8446
1        19150
2        46825
3        95011
4        68234
         ...
79995    23346
79996    11863
79997    92599
79998    73902
79999    83066
Name: index, Length: 80000, dtype: int64

In [28]:
y_train

       LOAN_APPROVAL
0                  1
1                  1
2                  1
3                  1
4                  1
...              ...
79995              1
79996              1
79997              1
79998              0
79999              1

[80000 rows x 1 columns]

## step 4 --> Training model using algorithm

In [29]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()

model.fit(X_train_trans,y_train)

C:\Users\vutuk\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier()

## step 5 -- Feature Engineering on Test Data

In [30]:
X_test

,age,job,marital,education,default,balance,housing_loan,personal_loan,contact,day,month,duration,campaign,pdays,previous,poutcome
60645,64,student,divorced,primary,0,28027,1,0,cellular,10,nov,312,15,391,1,failure
84599,43,admin,single,primary,0,107073,0,1,telephone,12,oct,1890,13,17,5,success
59801,28,retired,married,tertiary,1,18963,0,0,telephone,21,jun,1321,3,183,7,success
90055,42,admin,married,secondary,0,41272,0,0,telephone,9,aug,987,7,462,9,failure
94213,51,admin,married,tertiary,0,148694,1,1,telephone,10,sep,1576,18,81,4,success
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3081,24,services,married,tertiary,0,107632,1,0,cellular,10,feb,1297,17,373,6,success
98897,64,retired,single,tertiary,0,48442,1,0,telephone,27,aug,669,2,290,8,unknown
69223,57,retired,divorced,secondary,0,26277,1,1,cellular,19,jan,1905,11,482,9,success
34419,38,retired,single,secondary,1,80863,1,0,cellular,17,dec,1844,10,287,2,failure
58585,51,management,divorced,primary,0,33523,0,1,cellular,21,apr,1804,4,27,3,success

In [31]:
num_df = X_test[['age','balance','day','duration','campaign','pdays']]

In [32]:
cat_df = X_test.select_dtypes(include='object')

In [33]:
no_trans = X_test[['default','housing_loan','personal_loan','previous']]

In [34]:
## num trans
num_df_trans = scaler.transform(num_df)
num_df_trans

            age   balance       day  duration  campaign  pdays
60645  0.821429  0.197550  0.310345  0.143220  0.777778  0.784
84599  0.446429  0.717600  0.379310  0.944642  0.666667  0.036
59801  0.178571  0.137917  0.689655  0.655663  0.111111  0.368
90055  0.428571  0.284690  0.275862  0.486034  0.333333  0.926
94213  0.589286  0.991427  0.310345  0.785170  0.944444  0.164
...         ...       ...       ...       ...       ...    ...
3081   0.107143  0.721277  0.310345  0.643474  0.888889  0.748
98897  0.821429  0.331862  0.896552  0.324530  0.055556  0.582
69223  0.696429  0.186037  0.620690  0.952260  0.555556  0.966
34419  0.357143  0.545162  0.551724  0.921280  0.500000  0.576
58585  0.589286  0.233709  0.689655  0.900965  0.166667  0.056

[20000 rows x 6 columns]

In [35]:
## cat_df transformation 

cat_df_trans = OHE.transform(cat_df)
cat_df_trans

,job_admin,job_management,job_retired,job_services,job_student,job_technician,marital_divorced,marital_married,marital_single,education_primary,...,month_jul,month_jun,month_mar,month_may,month_nov,month_oct,month_sep,poutcome_failure,poutcome_success,poutcome_unknown
60645,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
84599,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
59801,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90055,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94213,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3081,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
98897,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
69223,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34419,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
58585,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [36]:
num_df_trans.reset_index(inplace=True)

In [37]:
cat_df_trans.reset_index(inplace=True)

In [38]:
no_trans.reset_index(inplace=True)

In [39]:
X_test_trans = pd.concat([num_df_trans,cat_df_trans,no_trans],axis=1)

In [40]:
X_test_trans

,index,age,balance,day,duration,campaign,pdays,index,job_admin,job_management,...,month_oct,month_sep,poutcome_failure,poutcome_success,poutcome_unknown,index,default,housing_loan,personal_loan,previous
0,60645,0.821429,0.197550,0.310345,0.143220,0.777778,0.784,60645,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,60645,0,1,0,1
1,84599,0.446429,0.717600,0.379310,0.944642,0.666667,0.036,84599,1.0,0.0,...,1.0,0.0,0.0,1.0,0.0,84599,0,0,1,5
2,59801,0.178571,0.137917,0.689655,0.655663,0.111111,0.368,59801,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,59801,1,0,0,7
3,90055,0.428571,0.284690,0.275862,0.486034,0.333333,0.926,90055,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,90055,0,0,0,9
4,94213,0.589286,0.991427,0.310345,0.785170,0.944444,0.164,94213,1.0,0.0,...,0.0,1.0,0.0,1.0,0.0,94213,0,1,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,3081,0.107143,0.721277,0.310345,0.643474,0.888889,0.748,3081,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,3081,0,1,0,6
19996,98897,0.821429,0.331862,0.896552,0.324530,0.055556,0.582,98897,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,98897,0,1,0,8
19997,69223,0.696429,0.186037,0.620690,0.952260,0.555556,0.966,69223,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,69223,0,1,1,9
19998,34419,0.357143,0.545162,0.551724,0.921280,0.500000,0.576,34419,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,34419,1,1,0,2
19999,58585,0.589286,0.233709,0.689655,0.900965,0.166667,0.056,58585,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,58585,0,0,1,3

In [41]:
X_test_trans.pop('index')

       index  index  index
0      60645  60645  60645
1      84599  84599  84599
2      59801  59801  59801
3      90055  90055  90055
4      94213  94213  94213
...      ...    ...    ...
19995   3081   3081   3081
19996  98897  98897  98897
19997  69223  69223  69223
19998  34419  34419  34419
19999  58585  58585  58585

[20000 rows x 3 columns]

In [42]:
y_test.reset_index(inplace=True)

In [43]:
y_test.pop('index')

0        60645
1        84599
2        59801
3        90055
4        94213
         ...
19995     3081
19996    98897
19997    69223
19998    34419
19999    58585
Name: index, Length: 20000, dtype: int64

## step 6 --> predicting on X_test_trans

In [44]:
y_pred = model.predict(X_test_trans)
y_pred

array([1, 1, 1, ..., 1, 1, 1], shape=(20000,))

## step 7 -- passing y_test(actual) and y_pred(model_prediction) to Evaluation Metric

In [45]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_pred)

0.6951

## How to save your production files

In [46]:
import joblib

joblib.dump({'model':model,'cat_encod':OHE,'num_encod':scaler},'model_prod_files.pkl')

['model_prod_files.pkl']

In [47]:
prod_files = joblib.load('model_prod_files.pkl')

In [48]:
prod_files['model']

KNeighborsClassifier()

In [49]:
prod_files['cat_encod']

OneHotEncoder(sparse_output=False)

In [50]:
prod_files['num_encod']

MinMaxScaler()